#ifndef YY_FONTDEF_H_
#define YY_FONTDEF_H_

#define yy_create_buffer	fontdef_yy_create_buffer
#define yy_delete_buffer	fontdef_yy_delete_buffer
#define yy_flex_debug	fontdef_yy_flex_debug
#define yy_flush_buffer		fontdef_yy_flush_buffer
#define yy_init_buffer		fontdef_yy_init_buffer
#define yy_load_buffer_state	fontdef_yy_load_buffer_state
#define yy_scan_buffer		fontdef_yy_scan_buffer
#define yy_scan_bytes		fontdef_yy_scan_bytes
#define yy_scan_string		fontdef_yy_scan_string
#define yy_switch_to_buffer	fontdef_yy_switch_to_buffer

#define yyact       fontdef_yyact
#define yyalloc	fontdef_yyalloc
#define yyback      fontdef_yyback
#define yybgin      fontdef_yybgin
#define yychar      fontdef_yychar
#define yychk       fontdef_yychk
#define yycrank     fontdef_yycrank
#define yydebug     fontdef_yydebug
#define yydef       fontdef_yydef
#define yyerrflag   fontdef_yyerrflag
#define yyestate    fontdef_yyestate
#define yyexca      fontdef_yyexca
#define yyextra     fontdef_yyextra
#define yyfnd       fontdef_yyfnd
#define yyfree			fontdef_yyfree
#define yyget_debug	fontdef_yyget_debug
#define yyget_in	fontdef_yyget_in
#define yyget_leng	fontdef_yyget_leng
#define yyget_lineno	fontdef_yyget_lineno
#define yyget_out	fontdef_yyget_out
#define yyget_text	fontdef_yyget_text
#define yyin        fontdef_yyin
#define yyinput     fontdef_yyinput
#define yyleng      fontdef_yyleng
#define yylex       fontdef_yylex
#define yylex_destroy		fontdef_yylex_destroy
#define yylineno    fontdef_yylineno
#define yylocale	fontdef_yylocale
#define yylook      fontdef_yylook
#define yylsp       fontdef_yylsp
#define yylstate    fontdef_yylstate
#define yylval      fontdef_yylval
#define yymatch     fontdef_yymatch
#define yymaxdepth  fontdef_yymaxdepth
#define yymorfg     fontdef_yymorfg
#define yynerrs     fontdef_yynerrs
#define yynls16		fontdef_yynls16
#define yynls_wchar	fontdef_yynls_wchar
#define yyolsp      fontdef_yyolsp
#define yyout       fontdef_yyout
#define yyoutput    fontdef_yyoutput
#define yypact      fontdef_yypact
#define yyparse     fontdef_yyparse
#define yypgo       fontdef_yypgo
#define yypop_buffer_state	fontdef_yypop_buffer_state
#define yyposix_point	fontdef_yyposix_point
#define yyprevious  fontdef_yyprevious
#define yyps        fontdef_yyps
#define yypush_buffer_state	fontdef_yypush_buffer_state
#define yypv        fontdef_yypv
#define yypvt       fontdef_yypvt
#define yyr1        fontdef_yyr1
#define yyr2        fontdef_yyr2
#define yyrealloc	fontdef_yyrealloc
#define yyreds      fontdef_yyreds
#define yyrestart		fontdef_yyrestart
#define yys         fontdef_yys
#define yysbuf      fontdef_yysbuf
#define yyset_debug		fontdef_yyset_debug
#define yyset_in	fontdef_yyset_in
#define yyset_lineno	fontdef_yyset_lineno
#define yyset_out	fontdef_yyset_out
#define yysptr      fontdef_yysptr
#define yystate     fontdef_yystate
#define yysvec      fontdef_yysvec
#define yytchar     fontdef_yytchar
#define yytext      fontdef_yytext
#define yytmp       fontdef_yytmp
#define yytoks      fontdef_yytoks
#define yytop       fontdef_yytop
#define yyunput     fontdef_yyunput
#define yyv         fontdef_yyv
#define yyval       fontdef_yyval
#define yyvstop     fontdef_yyvstop
#define yywrap      fontdef_yywrap

#endif /* YY_FONTDEF_H_ */
