#ifndef YY_LEVELS_H_
#define YY_LEVELS_H_

#define yy_create_buffer	levels_yy_create_buffer
#define yy_delete_buffer	levels_yy_delete_buffer
#define yy_flex_debug	levels_yy_flex_debug
#define yy_flush_buffer		levels_yy_flush_buffer
#define yy_init_buffer		levels_yy_init_buffer
#define yy_load_buffer_state	levels_yy_load_buffer_state
#define yy_scan_buffer		levels_yy_scan_buffer
#define yy_scan_bytes		levels_yy_scan_bytes
#define yy_scan_string		levels_yy_scan_string
#define yy_switch_to_buffer	levels_yy_switch_to_buffer

#define yyact       levels_yyact
#define yyalloc	levels_yyalloc
#define yyback      levels_yyback
#define yybgin      levels_yybgin
#define yychar      levels_yychar
#define yychk       levels_yychk
#define yycrank     levels_yycrank
#define yydebug     levels_yydebug
#define yydef       levels_yydef
#define yyerrflag   levels_yyerrflag
#define yyestate    levels_yyestate
#define yyexca      levels_yyexca
#define yyextra     levels_yyextra
#define yyfnd       levels_yyfnd
#define yyfree			levels_yyfree
#define yyget_debug	levels_yyget_debug
#define yyget_in	levels_yyget_in
#define yyget_leng	levels_yyget_leng
#define yyget_lineno	levels_yyget_lineno
#define yyget_out	levels_yyget_out
#define yyget_text	levels_yyget_text
#define yyin        levels_yyin
#define yyinput     levels_yyinput
#define yyleng      levels_yyleng
#define yylex       levels_yylex
#define yylex_destroy		levels_yylex_destroy
#define yylineno    levels_yylineno
#define yylocale	levels_yylocale
#define yylook      levels_yylook
#define yylsp       levels_yylsp
#define yylstate    levels_yylstate
#define yylval      levels_yylval
#define yymatch     levels_yymatch
#define yymaxdepth  levels_yymaxdepth
#define yymorfg     levels_yymorfg
#define yynerrs     levels_yynerrs
#define yynls16		levels_yynls16
#define yynls_wchar	levels_yynls_wchar
#define yyolsp      levels_yyolsp
#define yyout       levels_yyout
#define yyoutput    levels_yyoutput
#define yypact      levels_yypact
#define yyparse     levels_yyparse
#define yypgo       levels_yypgo
#define yypop_buffer_state	levels_yypop_buffer_state
#define yyposix_point	levels_yyposix_point
#define yyprevious  levels_yyprevious
#define yyps        levels_yyps
#define yypush_buffer_state	levels_yypush_buffer_state
#define yypv        levels_yypv
#define yypvt       levels_yypvt
#define yyr1        levels_yyr1
#define yyr2        levels_yyr2
#define yyrealloc	levels_yyrealloc
#define yyreds      levels_yyreds
#define yyrestart		levels_yyrestart
#define yys         levels_yys
#define yysbuf      levels_yysbuf
#define yyset_debug		levels_yyset_debug
#define yyset_in	levels_yyset_in
#define yyset_lineno	levels_yyset_lineno
#define yyset_out	levels_yyset_out
#define yysptr      levels_yysptr
#define yystate     levels_yystate
#define yysvec      levels_yysvec
#define yytchar     levels_yytchar
#define yytext      levels_yytext
#define yytmp       levels_yytmp
#define yytoks      levels_yytoks
#define yytop       levels_yytop
#define yyunput     levels_yyunput
#define yyv         levels_yyv
#define yyval       levels_yyval
#define yyvstop     levels_yyvstop
#define yywrap      levels_yywrap

#endif /* YY_LEVELS_H_ */
