#ifndef YY_SETTINGS_H_
#define YY_SETTINGS_H_

#define yy_create_buffer	settings_yy_create_buffer
#define yy_delete_buffer	settings_yy_delete_buffer
#define yy_flex_debug	settings_yy_flex_debug
#define yy_flush_buffer		settings_yy_flush_buffer
#define yy_init_buffer		settings_yy_init_buffer
#define yy_load_buffer_state	settings_yy_load_buffer_state
#define yy_scan_buffer		settings_yy_scan_buffer
#define yy_scan_bytes		settings_yy_scan_bytes
#define yy_scan_string		settings_yy_scan_string
#define yy_switch_to_buffer	settings_yy_switch_to_buffer

#define yyact       settings_yyact
#define yyalloc	settings_yyalloc
#define yyback      settings_yyback
#define yybgin      settings_yybgin
#define yychar      settings_yychar
#define yychk       settings_yychk
#define yycrank     settings_yycrank
#define yydebug     settings_yydebug
#define yydef       settings_yydef
#define yyerrflag   settings_yyerrflag
#define yyestate    settings_yyestate
#define yyexca      settings_yyexca
#define yyextra     settings_yyextra
#define yyfnd       settings_yyfnd
#define yyfree			settings_yyfree
#define yyget_debug	settings_yyget_debug
#define yyget_in	settings_yyget_in
#define yyget_leng	settings_yyget_leng
#define yyget_lineno	settings_yyget_lineno
#define yyget_out	settings_yyget_out
#define yyget_text	settings_yyget_text
#define yyin        settings_yyin
#define yyinput     settings_yyinput
#define yyleng      settings_yyleng
#define yylex       settings_yylex
#define yylex_destroy		settings_yylex_destroy
#define yylineno    settings_yylineno
#define yylocale	settings_yylocale
#define yylook      settings_yylook
#define yylsp       settings_yylsp
#define yylstate    settings_yylstate
#define yylval      settings_yylval
#define yymatch     settings_yymatch
#define yymaxdepth  settings_yymaxdepth
#define yymorfg     settings_yymorfg
#define yynerrs     settings_yynerrs
#define yynls16		settings_yynls16
#define yynls_wchar	settings_yynls_wchar
#define yyolsp      settings_yyolsp
#define yyout       settings_yyout
#define yyoutput    settings_yyoutput
#define yypact      settings_yypact
#define yyparse     settings_yyparse
#define yypgo       settings_yypgo
#define yypop_buffer_state	settings_yypop_buffer_state
#define yyposix_point	settings_yyposix_point
#define yyprevious  settings_yyprevious
#define yyps        settings_yyps
#define yypush_buffer_state	settings_yypush_buffer_state
#define yypv        settings_yypv
#define yypvt       settings_yypvt
#define yyr1        settings_yyr1
#define yyr2        settings_yyr2
#define yyrealloc	settings_yyrealloc
#define yyreds      settings_yyreds
#define yyrestart		settings_yyrestart
#define yys         settings_yys
#define yysbuf      settings_yysbuf
#define yyset_debug		settings_yyset_debug
#define yyset_in	settings_yyset_in
#define yyset_lineno	settings_yyset_lineno
#define yyset_out	settings_yyset_out
#define yysptr      settings_yysptr
#define yystate     settings_yystate
#define yysvec      settings_yysvec
#define yytchar     settings_yytchar
#define yytext      settings_yytext
#define yytmp       settings_yytmp
#define yytoks      settings_yytoks
#define yytop       settings_yytop
#define yyunput     settings_yyunput
#define yyv         settings_yyv
#define yyval       settings_yyval
#define yyvstop     settings_yyvstop
#define yywrap      settings_yywrap

#endif /* YY_SETTINGS_H_ */
